AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'test/**/*.rb'
    - 'test/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# TODO: consider tightening the rule (default: 10)
Metrics/MethodLength:
  Max: 25
